clc;
clear all;
x=linspace(0,2*pi,500);
y1=sin(x);
y2=cos(x);
y3=2*sin(x).*cos(x);
y4=sin(x)./cos(x);
subplot(2,2,1);
plot(y1);
title('sin x');
subplot(2,2,2);
plot(y2);
title('cos x');
subplot(2,2,3);
plot(y3);
title('2sin x*cos x');
subplot(2,2,4);
plot(y4);
title('sin x/cos x');
